name: Development build

on:
  push:
    branches:
      - dev

env:
  APPLICATION_NAME: "koreki"

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Details extraction
        id: details
        run: |
          echo "version=${GITHUB_REF##*/}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    outputs:
      version: ${{ steps.details.outputs.version }}

  build:
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set environment variables
        run: |
          echo "VERSION=${{ needs.setup.outputs.version }}" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          check-latest: true
          server-id: GitHubPackages
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: ./gradlew build sourcesJar javadocJar -x test

      - name: Create output directory
        run: mkdir -p output

      - name: Move artifacts
        run: |
          mv build/libs/koreki-${{ env.VERSION }}.jar          output/${{ env.APPLICATION_NAME }}-${{ env.VERSION }}.jar
          mv build/libs/koreki-${{ env.VERSION }}-javadoc.jar  output/${{ env.APPLICATION_NAME }}-${{ env.VERSION }}-javadoc.jar
          mv build/libs/koreki-${{ env.VERSION }}-sources.jar  output/${{ env.APPLICATION_NAME }}-${{ env.VERSION }}-sources.jar

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build artifacts
          path: output/

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}